#!/bin/bash
# SPDX-License-Identifier: MIT
# SPDX-FileCopyrightText: Copyright 2024 SUSE LLC
# SPDX-FileCopyrightText: Copyright 2024 Richard Brown

set -euo pipefail

# Setup logging
exec 3>&1 4>&2
trap 'exec 2>&4 1>&3' 0 1 2 3
exec 1>>/var/log/aeon-check.log 2>&1

# Load optional configuration
FDE_ENABLED="true"
if test -f /etc/sysconfig/fde-tools; then
    . /etc/sysconfig/fde-tools
fi

# Check for TPM2 presence
has_tpm2() {
    tpm2_getcap properties-fixed &>/dev/null
}

boo1228416() {
    # Problem: TPM2 using pcr hashes not pcrlock
    # Solution: Configure and enrol pcrlock for FDE

    rootdev=/dev/$(dmsetup deps -o devname /dev/mapper/aeon_root | cut -d '(' -f2 | cut -d ')' -f1)
    tpm2hashpcrs=$(cryptsetup luksDump ${rootdev} | grep 'tpm2-hash-pcrs:' | tr -d ' \t' | cut -d ':' -f2)
    tpm2pcrlock=$(cryptsetup luksDump ${rootdev} | grep 'tpm2-pcrlock:' | tr -d ' \t' | cut -d ':' -f2)

    if [ "${tpm2hashpcrs}" == "7" ] && [ "${tpm2pcrlock}" == "false" ]; then
        echo "boo1228416 detected - TPM2 using pcr hashes not pcrlock - correcting"

        keyfile=$(mktemp /tmp/aeon-check.XXXXXXXXXX)
        dd bs=512 count=4 if=/dev/urandom of=${keyfile} iflag=fullblock
        chmod 400 ${keyfile}

        tpm2slot=$(systemd-cryptenroll ${rootdev} | grep tpm2 | xargs | cut -d ' ' -f1)

        cryptsetup luksAddKey --token-only --batch-mode --new-key-slot=31 ${rootdev} ${keyfile}
        systemd-cryptenroll --wipe-slot=${tpm2slot} ${rootdev}
        systemd-cryptenroll --unlock-key-file=${keyfile} --tpm2-device=auto ${rootdev}
        systemd-cryptenroll --wipe-slot=31 ${rootdev}
        rm ${keyfile}

        echo "boo1228416 corrected"
    fi
}

boo1234234() {
    # Problem: TPM2 enrolments failing due to PCR0
    # Solution: Remove PCR0 from FDE seal list

    if test -e /etc/sysconfig/fde-tools ; then
        . /etc/sysconfig/fde-tools

        if [ "${FDE_SEAL_PCR_LIST}" = "0,4,5,7,9" ]; then
            echo "boo1234234 detected - PCR0 included - correcting"
            echo "FDE_SEAL_PCR_LIST=4,5,7,9" > /etc/sysconfig/fde-tools
            sdbootutil -v update-predictions
            echo "boo1234234 corrected"
        fi
    fi
}

boo1243182() {
    # Problem: Not using ZYPP_SINGLE_RPMTRANS
    # Solution: Enable it in zypp.conf

    if ! grep -qxF 'techpreview.ZYPP_SINGLE_RPMTRANS=1' /etc/zypp/zypp.conf ; then
         echo 'boo1243182 detected - Not using ZYPP_SINGLE_RPMTRANS - correcting'
         echo 'techpreview.ZYPP_SINGLE_RPMTRANS=1' >> /etc/zypp/zypp.conf
         echo 'boo1243182 corrected'
    fi
}

# Start main logic

if [ "${FDE_ENABLED}" != "true" ]; then
    echo "FDE explicitly disabled via configuration – skipping TPM2 checks"
else
    if has_tpm2; then
        echo "TPM2 detected – applying relevant FDE fixes"
        boo1228416
        boo1234234
    else
        echo "No TPM2 detected – skipping FDE configuration"
    fi
fi

# Active fixes unrelated to TPM/FDE
boo1243182